### ISSUE TITLE
Peer to peer review

### ISSUE THREAD

**Issue by StarMindz** [MarcoOquendoC/CapstoneAPEC#1]
# Good job Marco with your design and code. 
## Your code is written professionally and the website also looks very beautiful. I commend you for that!
![](https://media.giphy.com/media/3o72FcJmLzIdYJdmDe/giphy.gif)

## However, there's a little issue that you can improve on to make your code even better:
You can add a "More" button in the speakers section of the mobile version of your website to display some initially hidden speaker content when clicked. This would make your website much better. 
Happy coding 🥂

**Comment by MarcoOquendoC** [comment]
Feature implemented Thanks
